name: thread
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter
  # Navigation
  # go_router: ^14.2.0
  # Logger
  # l: ^5.0.0-pre.2
  logging: ^1.2.0
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  # Networking
  dio: ^5.4.2+1
  dio_smart_retry: ^6.0.0
  shared_preferences: ^2.2.2
  rxdart: ^0.28.0-dev.0
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.6
  # Utility
  collection: any
  async: any
  path: any

  # Annotation
  meta: any
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  pubspec_generator: ^4.1.0-pre.1
  json_serializable: ^6.7.1
  # dart run flutter_launcher_icons -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.6


  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/



flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120