name: thread
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  async: any
  path: any
  collection: any
  meta: any


  dio: ^5.5.0
  dio_smart_retry: ^6.0.0
  shared_preferences: ^2.3.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

  flutter_native_splash: ^2.4.1

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  web: ^1.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.6.0
  pubspec_generator: ^4.1.0-pre.1
  json_serializable: ^6.8.0
  # dart run flutter_launcher_icons -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
  build_runner: ^2.4.12


  flutter_lints: ^4.0.0
  freezed: ^2.5.2


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/



flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120

flutter_native_splash:
  color: "#42a5f5"

  #image: assets/splash.png

  #branding: assets/dart.png
  #branding_mode: bottom
  #branding_bottom_padding: 24

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  android_12:
    #image: assets/android12splash.png
    color: "#8655f5"
    #icon_background_color: "#111111"
    #branding: assets/dart.png
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"

  #android: false
  #ios: false
  #web: false

  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_bottom_padding_android: 24
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_bottom_padding_ios: 24
  #branding_dark_ios: assets/dart_dark-ios.png
  #branding_web: assets/brand-web.gif
  #branding_dark_web: assets/dart_dark-web.gif

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #android_screen_orientation: sensorLandscape

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
