name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Install FTP client
        run: sudo apt-get install -y ftp

      - name: Upload APK to Server via FTP
        run: |
          ftp -inv ${{ secrets.SSH_SERVER }} <<EOF
          user ${{ secrets.SSH_USERNAME }} ${{ secrets.SSH_PASSWORD }}
          binary
          cd ${{ secrets.DEPLOY_PATH }}
          put build/app/outputs/flutter-apk/app-release.apk
          bye
          EOF
