name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Create config directory
        run: mkdir -p config

      - name: Create production.json file
        run: echo '${{ secrets.CONFIG_PROD_FILE }}' > config/production.json

      - name: Validate JSON file
        run: |
          if ! jq . config/production.json > /dev/null 2>&1; then
            echo "Invalid JSON format in config/production.json"
            exit 1
          fi

      - name: Build APK
        env:
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        run: flutter build apk --release --dart-define-from-file=config/production.json

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Upload APK to Server via SFTP
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} sftp -o StrictHostKeyChecking=no -P 22 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }} <<EOF
          cd ${{ secrets.DEPLOY_PATH }}
          put build/app/outputs/flutter-apk/app-release.apk
          bye
          EOF
